import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { ConvexClientProvider } from "@/provider/convex-client-provider";
import ModalProvider from "@/provider/modal-provider";
import RenameModal from "@/components/modals/rename-modal";

import { LiveblocksProvider } from "@liveblocks/react";

const NunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-nunito-sans",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.variable}`}>
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        >
          <ConvexClientProvider>
            {children}
            <RenameModal />
            <Toaster />
            <ModalProvider />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
